version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studio_bookings
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: ../backend
    env_file:
      - ../backend/.env
    ports:
      - '4000:4000'
    depends_on:
      - db
  frontend:
    build: ../frontend
    ports:
      - '3000:3000'
    depends_on:
      - api
volumes:
  db_data:
